version: "3.5"

services:
  service-sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: database-sql
    restart: always
    ports:
    - 1434:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Mellizo55
    networks:
    -  mi-red

networks:
   mi-red:
    name: micro