version: "3.5"

services:
  rabbitmq-service:
    image: rabbitmq:3.8.13-management
    container_name: rabbitmq-service
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=Mellizo55
      - RABBITMQ_DEFAULT_PASS=Mellizo55
    ports:
    - 5672:5672
    - 15672:15672
    networks:
    - mi-red
  consul-service:
    image: consul:1.9.10
    container_name: consul-service
    restart: always
    ports:
    - 8500:8500
    networks:
    - mi-red
  fabio-service:
    image: fabiolb/fabio:1.5.15-go1.15.5
    container_name: fabio-service
    restart: always
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consul-service:8500
    ports:
    - 9998:9998
    - 9999:9999
    networks:
    - mi-red
    depends_on:
    - consul-service
  nacos-service:
    image: nacos/nacos-server:v2.0.3
    container_name: nacos-service 
    restart: always
    environment:
    - MODE=standalone
    ports:
    - 8848:8848
    networks:
    - mi-red

networks:
  mi-red:
    name: micro